// Authentication
export const GET_AUTHSTATE = 'GET_AUTHSTATE';
export const LOG_OUT = 'LOG_OUT';

// Calendar
export const GET_CALENDAR_DATA = 'GET_CALENDAR_DATA';

// Parking spots
export const MY_PARKINGS = 'MY_PARKINGS';
export const GET_PARKING_SPOTS = 'GET_PARKING_SPOTS';
export const DELETE_RESERVATION = 'DELETE_RESERVATION';

// Reservation
export const RESERVE_SPOTS = 'RESERVE_SPOTS';

// Errors
export const GENERAL_ERROR = 'GENERAL_ERROR';
export const NETWORK_ERROR = 'NETWORK_ERROR';
export const RESERVATION_FAILED = 'RESERVATION_FAILED';
export const DELETE_RESERVATION_FAILED = 'DELETE_RESERVATION_FAILED';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const PASSWORD_LOGIN_ERROR = 'PASSWORD_LOGIN_ERROR';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';

// Loading
export const SET_LOADING_STATE = 'SET_LOADING_STATE';
export const REMOVE_LOADING_STATE = 'REMOVE_LOADING_STATE';
